POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ilppc2hhbiBTaWRkaXF1ZSIsImlkIjoiNjJkZDY0NGRmYWY0YjQ3OWVkZDk1NGNjIiwiaWF0IjoxNjU4NjgxODU1LCJleHAiOjE2NTg2ODU0NTV9.gDhCeGMJ7hl0qv628YcWQC0ObqEU5DgcpmrpFPR--6o

{
    "title":"new blog with assigned user",
    "author":"El Storko",
    "url":"www.furious5.com",
    "likes":"232",
    "userId":"62dd6525a02ec9fd9e0b617b"
}